version: '2.0'

services:
  postgresql:
    container_name: db_postgresql
    image: bitnami/postgresql:16.2.0
    ports:
     - '5432:5432'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - ./database:/docker-entrypoint-initdb.d
  auth:
    container_name: auth-keycloak
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=project
      - KEYCLOAK_ADMIN_PASSWORD=project
    depends_on:
      - postgresql
  frontend:
    container_name: frontend_react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  emulator:
    container_name: emulator_flask
    build: ./emulator
    ports:
     - "5000:5000"
    volumes:
    - ./emulator:/app
volumes:
  postgresql_data:
    driver: local