version: '2.2'

services:
  postgresql:
    container_name: db_postgresql
    image: bitnami/postgresql:16.2.0
    ports:
     - '5432:5432'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - ./database:/docker-entrypoint-initdb.d
  auth:
    container_name: auth-keycloak
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=project
      - KEYCLOAK_ADMIN_PASSWORD=project
    depends_on:
      - postgresql
  frontend:
    container_name: frontend_react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    container_name: backend_django
    build:
     context: ./backend
     dockerfile: Dockerfile
    ports:
    - "8000:8000"
  emulator1:
    container_name: emulator_flask_1
    build: 
      context: ./emulator
      args:
        - PORT=5000
    ports:
     - "5000:5000"
  emulator2:
    container_name: emulator_flask_2
    build: 
      context: ./emulator
      args:
        - PORT=5001
    ports:
     - "5001:5001"
volumes:
  postgresql_data:
    driver: local