# Generated by Django 5.0.3 on 2024-03-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('circuit_name', models.CharField(max_length=100)),
                ('connected_object', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PowerStations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('measurement', models.CharField(max_length=100)),
                ('circuit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.circuits')),
            ],
        ),
        migrations.AddField(
            model_name='circuits',
            name='power_station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.powerstations'),
        ),
    ]
